class Bab:
    NONE                 = "None"
    NASARA_YANSURU       = "نَصَرَ- يَنْصُرُ"
    DARABA_YADRIBU       = "ضَرَبَ - يَضْرِبُ"
    SAMIA_YASMAU         = "سَمِعَ - يَسْمَعُ"
    FATAHA_YAFTAHU       = "فَتَحَ - يَفْتَحُ"
    BABUL_IFAL           = "بَابُ الإفْعَالِ"
    BABUT_TAFEL          = "بَابُ التَّفْعِيلِ"
    BABUT_TAFAUL         = "بَابُ التَّفَعُّلِ"
    BABUL_IFTEAL         = "بَابُ الاِفْتِعَال"
