class Bab:
    NONE                 = "None"
    NASARA_YANSURU       = "نَصَرَ- يَنْصُرُ"
    DARABA_YADRIBU       = "ضَرَبَ - يَضْرِبُ"
    SAMIA_YASMAU         = "سَمِعَ - يَسْمَعُ"
    FATAHA_YAFTAHU       = "فَتَحَ - يَفْتَحُ"
    BABUL_IFALI           = "بَابُ الإفْعَالِ"
    BABUT_TAFELI          = "بَابُ التَّفْعِيلِ"
    BABUT_TAFAULI         = "بَابُ التَّفَعُّلِ"
    BABUL_IFTEALI         = "بَابُ الاِفْتِعَالِ"
    BABUL_ISTEFALI        = "بَابُ الاِسْتِفْعَالِ"
    BABUL_MUFAALATI      = "بَابُ المُفَاعَلَةِ"
