class GSheetValues:
    BAB_SHEET_MAPPING = {
        "نَصَرَ- يَنْصُرُ"     : 1,
        "ضَرَبَ - يَضْرِبُ"    : 2,
        "سَمِعَ - يَسْمَعُ"    : 3,
        "فَتَحَ - يَفْتَحُ"    : 4,
        "بَابُ الإفْعَالِ"    : 5
    }

    BAB_SHEET_NAME = "বাব"
    BAB_CURRENT_ROW_OFFSET = 2

    SAHEE_MASDER        = "صحيح"
    GAIRE_SAHEE_MASDER  = "غير صحيح"

    BAB_COl     = 5
    ROOT_COl    = 4
    MASDER_COl  = 3

    PAST_FORM_3RD_PERSON_CELL_COL = 8
    PAST_FORM_2ND_PERSON_CELL_COL = 7
    PAST_FORM_1ST_PERSON_CELL_COL = 6

    PRESENT_FORM_3RD_PERSON_CELL_COL = 11
    PRESENT_FORM_2ND_PERSON_CELL_COL = 10
    PRESENT_FORM_1ST_PERSON_CELL_COL = 9

    NEGATIVE_PAST_FORM_3RD_PERSON_CELL_COL = 14
    NEGATIVE_PAST_FORM_2ND_PERSON_CELL_COL = 13
    NEGATIVE_PAST_FORM_1ST_PERSON_CELL_COL = 12

    NEGATIVE_PRESENT_FORM_3RD_PERSON_CELL_COL = 17
    NEGATIVE_PRESENT_FORM_2ND_PERSON_CELL_COL = 16
    NEGATIVE_PRESENT_FORM_1ST_PERSON_CELL_COL = 15

    ORDER_FORM_2ND_PERSON_CELL_COL  = 18
    FORBID_FORM_2ND_PERSON_CELL_COL = 19

    NEGATIVE_FUTURE_FORM_3RD_PERSON_CELL_COL = 22
    NEGATIVE_FUTURE_FORM_2ND_PERSON_CELL_COL = 21
    NEGATIVE_FUTURE_FORM_1ST_PERSON_CELL_COL = 20

    FOR_PRESENT_FORM_3RD_PERSON_CELL_COL = 25
    FOR_PRESENT_FORM_2ND_PERSON_CELL_COL = 24
    FOR_PRESENT_FORM_1ST_PERSON_CELL_COL = 23

    OBJECT_PAST_FORM_3RD_PERSON_CELL_COL = 28
    OBJECT_PAST_FORM_2ND_PERSON_CELL_COL = 27
    OBJECT_PAST_FORM_1ST_PERSON_CELL_COL = 26
    OBJECT_PRESENT_FORM_3RD_PERSON_CELL_COL = 31
    OBJECT_PRESENT_FORM_2ND_PERSON_CELL_COL = 30
    OBJECT_PRESENT_FORM_1ST_PERSON_CELL_COL = 29