class GSheetValues:
    GSHEET_NAME = "Arabic Verb"
    FEL_TAB_NAME = "ফেল"

    PAST_FORM_3RD_PERSON_CELL_COL = 7
    PAST_FORM_2ND_PERSON_CELL_COL = 6
    PAST_FORM_1ST_PERSON_CELL_COL = 5
    PAST_FORM_1ST_PERSON_CELL_ROW = 3

    PRESENT_FORM_3RD_PERSON_CELL_COL = 10
    PRESENT_FORM_2ND_PERSON_CELL_COL = 9
    PRESENT_FORM_1ST_PERSON_CELL_COL = 8

    ORDER_FORM_2ND_PERSON_CELL_COL = 10
    FORBID_FORM_2ND_PERSON_CELL_COL = 11
